include(CheckIncludeFileCXX)
include(CheckCXXSymbolExists)

check_include_file_cxx(cfloat HAVE_CFLOAT)
check_include_file_cxx(cmath HAVE_CMATH)
check_include_file_cxx(cieeefp HAVE_CIEEEFP)
check_include_file_cxx(float.h HAVE_FLOAT_H)
check_include_file_cxx(math.h HAVE_MATH_H)
check_include_file_cxx(ieeefp.h HAVE_IEEEFP_H)

if(HAVE_CFLOAT)
	list(APPEND COIN_CHECK_HEADERS "cfloat")
endif()
if(HAVE_CMATH)
	list(APPEND COIN_CHECK_HEADERS "cmath")
endif()
if(HAVE_CIEEEFP)
	list(APPEND COIN_CHECK_HEADERS "cieeefp")
endif()
if(HAVE_FLOAT_H)
	list(APPEND COIN_CHECK_HEADERS "float.h")
endif()
if(HAVE_MATH_H)
	list(APPEND COIN_CHECK_HEADERS "math.h")
endif()
if(HAVE_IEEEFP_H)
	list(APPEND COIN_CHECK_HEADERS "ieeefp.h")
endif()

check_cxx_symbol_exists(finite "${COIN_CHECK_HEADERS}" HAVE_FINITE)
check_cxx_symbol_exists(_finite "${COIN_CHECK_HEADERS}" HAVE__FINITE)
check_cxx_symbol_exists(isfinite "${COIN_CHECK_HEADERS}" HAVE_ISFINITE)
check_cxx_symbol_exists(isnan "${COIN_CHECK_HEADERS}" HAVE_ISNAN)
check_cxx_symbol_exists(_isnan "${COIN_CHECK_HEADERS}" HAVE__ISNAN)
check_cxx_symbol_exists(isnand "${COIN_CHECK_HEADERS}" HAVE_ISNAND)

if(HAVE_FINITE)
	set(COIN_C_FINITE finite)
elseif(HAVE__FINITE)
	set(COIN_C_FINITE _finite)
elseif(HAVE_ISFINITE)
	set(COIN_C_FINITE isfinite)
else()
	message(FATAL_ERROR "C-function for inf check is undefined")
endif()

if(HAVE_ISNAN)
	set(COIN_C_ISNAN isnan)
elseif(HAVE__ISNAN)
	set(COIN_C_ISNAN _isnan)
elseif(HAVE_ISNAND)
	set(COIN_C_ISNAN isnand)
else()
	message(FATAL_ERROR "C-function for isnan check is undefined")
endif()

set(COIN_INT64_T "long long")
set(COIN_UINT64_T "unsigned long long")
set(COIN_INTPTR_T "int *")
